In [4]:
import numpy as np
import pandas as pd
from rex.resource_extraction import MultiYearWindX

#lat, lon = 41.101219, -83.644394
#myr = MultiYearWindX('/campaign/tap/CONUS/wtk/60min/2019/conus_2019.h5', hsds=False)

# For Alaska data (uncomment):
lat, lon = 64.503889, -165.399444
myr = MultiYearWindX('/campaign/tap/Alaska_Production/2018/alaska_2018.h5', hsds=False)

dt = myr.time_index
dt = pd.DataFrame({"datetime": dt[:]}, index=range(0,dt.shape[0]))
dt = dt["datetime"]

# Find index of the nearest gridpoint
dd, ii = myr.tree.query((lat, lon), 1)

wind_df = pd.DataFrame(index = dt.index)
wind_df["datetime"] = dt

ws_source = "windspeed_40m"
wind_df[ws_source] = myr[ws_source, 0:len(dt)+1, ii]
wd_source = "winddirection_40m"
wind_df[wd_source] = myr[wd_source, 0:len(dt)+1, ii]

display(wind_df)

                      datetime  windspeed_40m  winddirection_40m
0    2018-01-01 00:00:00+00:00      19.760000          63.990002
1    2018-01-01 01:00:00+00:00      19.020000          65.260002
2    2018-01-01 02:00:00+00:00      17.790001          69.750000
3    2018-01-01 03:00:00+00:00      16.040001          74.309998
4    2018-01-01 04:00:00+00:00      14.850000          76.449997
...                        ...            ...                ...
8755 2018-12-31 19:00:00+00:00       8.870000          82.660004
8756 2018-12-31 20:00:00+00:00       7.390000         101.470001
8757 2018-12-31 21:00:00+00:00       8.010000         103.129997
8758 2018-12-31 22:00:00+00:00       6.680000          80.029999
8759 2018-12-31 23:00:00+00:00       6.360000         107.930000

[8760 rows x 3 columns]

In [5]:
print(myr.datasets)

['boundary_layer_height', 'coordinates', 'friction_velocity_2m', 'inversemoninobukhovlength_2m', 'latent_heat_flux', 'meta', 'precipitation_0m', 'pressure_0m', 'pressure_100m', 'pressure_200m', 'pressure_500m', 'relativehumidity_2m', 'sensible_heat_flux', 'skin_temperature', 'temperature_1000m', 'temperature_100m', 'temperature_200m', 'temperature_20m', 'temperature_2m', 'temperature_300m', 'temperature_40m', 'temperature_500m', 'temperature_60m', 'temperature_80m', 'time_index', 'turbulent_kinetic_energy_1000m', 'turbulent_kinetic_energy_100m', 'turbulent_kinetic_energy_200m', 'turbulent_kinetic_energy_20m', 'turbulent_kinetic_energy_300m', 'turbulent_kinetic_energy_40m', 'turbulent_kinetic_energy_500m', 'turbulent_kinetic_energy_60m', 'turbulent_kinetic_energy_80m', 'vertical_windspeed_120m', 'vertical_windspeed_200m', 'vertical_windspeed_20m', 'vertical_windspeed_40m', 'vertical_windspeed_500m', 'vertical_windspeed_80m', 'virtual_potential_temperature_1000m', 'virtual_potential_temperature_100m', 'virtual_potential_temperature_200m', 'virtual_potential_temperature_20m', 'virtual_potential_temperature_2m', 'virtual_potential_temperature_300m', 'virtual_potential_temperature_40m', 'virtual_potential_temperature_500m', 'virtual_potential_temperature_60m', 'virtual_potential_temperature_80m', 'winddirection_1000m', 'winddirection_100m', 'winddirection_10m', 'winddirection_120m', 'winddirection_140m', 'winddirection_160m', 'winddirection_180m', 'winddirection_200m', 'winddirection_20m', 'winddirection_250m', 'winddirection_300m', 'winddirection_40m', 'winddirection_500m', 'winddirection_60m', 'winddirection_80m', 'windspeed_1000m', 'windspeed_100m', 'windspeed_10m', 'windspeed_120m', 'windspeed_140m', 'windspeed_160m', 'windspeed_180m', 'windspeed_200m', 'windspeed_20m', 'windspeed_250m', 'windspeed_300m', 'windspeed_40m', 'windspeed_500m', 'windspeed_60m', 'windspeed_80m']